FROM eclipse-temurin:21-jdk AS build
WORKDIR /app
COPY .. .
RUN chmod +x ./gradlew
RUN ./gradlew build --no-daemon

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8075
ENTRYPOINT ["java", "-jar", "app.jar"]